# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: U:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_xbar_0/ublaze_system_xbar_0.xci
# IP: The module: 'ublaze_system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_xbar_0/ublaze_system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: U:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_xbar_0/ublaze_system_xbar_0.xci
# IP: The module: 'ublaze_system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_xbar_0/ublaze_system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
