# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: U:/Documents/SoC/TP/basys3_master.xdc

# Block Designs: bd/SEG7_upgrade/SEG7_upgrade.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade || ORIG_REF_NAME==SEG7_upgrade} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_clk_wiz_0_0/SEG7_upgrade_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_clk_wiz_0_0 || ORIG_REF_NAME==SEG7_upgrade_clk_wiz_0_0} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_axi_uartlite_0_0/SEG7_upgrade_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_axi_uartlite_0_0 || ORIG_REF_NAME==SEG7_upgrade_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_microblaze_0_2/SEG7_upgrade_microblaze_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_microblaze_0_2 || ORIG_REF_NAME==SEG7_upgrade_microblaze_0_2} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_dlmb_v10_1/SEG7_upgrade_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_dlmb_v10_1 || ORIG_REF_NAME==SEG7_upgrade_dlmb_v10_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_ilmb_v10_1/SEG7_upgrade_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_ilmb_v10_1 || ORIG_REF_NAME==SEG7_upgrade_ilmb_v10_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_dlmb_bram_if_cntlr_1/SEG7_upgrade_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==SEG7_upgrade_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_ilmb_bram_if_cntlr_1/SEG7_upgrade_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==SEG7_upgrade_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_lmb_bram_1/SEG7_upgrade_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_lmb_bram_1 || ORIG_REF_NAME==SEG7_upgrade_lmb_bram_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_xbar_1/SEG7_upgrade_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_xbar_1 || ORIG_REF_NAME==SEG7_upgrade_xbar_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_microblaze_0_axi_periph_1/SEG7_upgrade_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_microblaze_0_axi_periph_1 || ORIG_REF_NAME==SEG7_upgrade_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_microblaze_0_axi_intc_0/SEG7_upgrade_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_microblaze_0_axi_intc_0 || ORIG_REF_NAME==SEG7_upgrade_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_microblaze_0_xlconcat_0/SEG7_upgrade_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_microblaze_0_xlconcat_0 || ORIG_REF_NAME==SEG7_upgrade_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_mdm_1_1/SEG7_upgrade_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_mdm_1_1 || ORIG_REF_NAME==SEG7_upgrade_mdm_1_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_rst_clk_wiz_0_100M_1/SEG7_upgrade_rst_clk_wiz_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_rst_clk_wiz_0_100M_1 || ORIG_REF_NAME==SEG7_upgrade_rst_clk_wiz_0_100M_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_axi_timer_0_0/SEG7_upgrade_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_axi_timer_0_0 || ORIG_REF_NAME==SEG7_upgrade_axi_timer_0_0} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_axi_gpio_0_1/SEG7_upgrade_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_axi_gpio_0_1 || ORIG_REF_NAME==SEG7_upgrade_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_axi_gpio_1_1/SEG7_upgrade_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_axi_gpio_1_1 || ORIG_REF_NAME==SEG7_upgrade_axi_gpio_1_1} -quiet] -quiet

# IP: bd/SEG7_upgrade/ip/SEG7_upgrade_SEG7_IP_0_1/SEG7_upgrade_SEG7_IP_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SEG7_upgrade_SEG7_IP_0_1 || ORIG_REF_NAME==SEG7_upgrade_SEG7_IP_0_1} -quiet] -quiet

# XDC: bd/SEG7_upgrade/SEG7_upgrade_ooc.xdc
