# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     rii_C_Release
#     rii_C_Release_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

ADI_DSP=C:\Program Files (x86)\Analog Devices\VisualDSP 4.5


# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

RM=cmd /C del /F /Q

#
# Begin "rii_C_Release" configuration
#

ifeq ($(MAKECMDGOALS),rii_C_Release)

rii_C_Release : ./Release/rii_C.dxe 

./Release/rii.doj :../../VisualDSP_res/Fichiers\ sources\ du\ TP2/rii.c $(VDSP)/212xx/include/stdio.h $(VDSP)/212xx/include/stdio_21xxx.h $(VDSP)/212xx/include/stdlib.h carre_100b.dat 
	@echo "..\..\VisualDSP_res\Fichiers sources du TP2\rii.c"
	$(VDSP)/cc21k.exe -c ..\..\VisualDSP_res\Fichiers\ sources\ du\ TP2\rii.c -file-attr ProjectName=rii_C -O -Ov100 -structs-do-not-overlap -no-multiline -double-size-32 -warn-protos -proc ADSP-21262 -o .\Release\rii.doj -MM

./Release/rii_C.dxe :./Release/rii.doj ../../VisualDSP_res/Fichiers\ sources\ du\ TP2/ADSP-21262.LDF $(VDSP)/212xx/lib/2126x_rev_0.0/262_hdr.doj Release/rii.doj $(VDSP)/212xx/lib/2126x_rev_0.0/libc26x.dlb $(VDSP)/212xx/lib/2126x_rev_0.0/libio.dlb $(VDSP)/212xx/lib/2126x_rev_0.0/libdsp26x.dlb $(VDSP)/212xx/lib/2126x_rev_0.0/libcpp.dlb $(VDSP)/212xx/lib/2126x_rev_0.0/libeh.dlb $(VDSP)/212xx/lib/2126x_rev_0.0/libcpprt.dlb 
	@echo "Linking..."
	$(VDSP)/cc21k.exe .\Release\rii.doj -T ..\..\VisualDSP_res\Fichiers\ sources\ du\ TP2\ADSP-21262.LDF -flags-link -ip -L .\Release -flags-link -e -flags-link -od,.\Release -o .\Release\rii_C.dxe -proc ADSP-21262 -flags-link -MM

endif

ifeq ($(MAKECMDGOALS),rii_C_Release_clean)

rii_C_Release_clean:
	-$(RM) ".\Release\rii.doj"
	-$(RM) ".\Release\rii_C.dxe"
	-$(RM) ".\Release\*.ipa"
	-$(RM) ".\Release\*.opa"
	-$(RM) ".\Release\*.ti"
	-$(RM) ".\*.rbld"

endif


