# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     rif_ASMM_Debug
#     rif_ASMM_Debug_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

ADI_DSP=C:\Program Files (x86)\Analog Devices\VisualDSP 4.5


# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

RM=cmd /C del /F /Q

#
# Begin "rif_ASMM_Debug" configuration
#

ifeq ($(MAKECMDGOALS),rif_ASMM_Debug)

rif_ASMM_Debug : Debug/rif_ASMM.dxe 

./Debug/rif.doj :../../VisualDSP_res/Fichiers\ sources\ du\ TP1/rif.asm 
	@echo "..\..\VisualDSP_res\Fichiers sources du TP1\rif.asm"
	$(VDSP)/easm21k.exe ..\..\VisualDSP_res\Fichiers\ sources\ du\ TP1\rif.asm -proc ADSP-21262 -g -o .\Debug\rif.doj -MM

./Debug/riftest.doj :../../VisualDSP_res/Fichiers\ sources\ du\ TP1/riftest.asm $(VDSP)/212xx/include/def21262.h $(VDSP)/212xx/include/def21266.h rifcoeffs.dat 
	@echo "..\..\VisualDSP_res\Fichiers sources du TP1\riftest.asm"
	$(VDSP)/easm21k.exe ..\..\VisualDSP_res\Fichiers\ sources\ du\ TP1\riftest.asm -proc ADSP-21262 -g -o .\Debug\riftest.doj -MM

Debug/rif_ASMM.dxe :../../VisualDSP_res/Fichiers\ sources\ du\ TP1/ADSP-21262_ASM.LDF ./Debug/rif.doj ./Debug/riftest.doj $(VDSP)/212xx/lib/2126x_rev_0.0/libc26x.dlb $(VDSP)/212xx/lib/2126x_rev_0.0/libio.dlb $(VDSP)/212xx/lib/2126x_rev_0.0/libdsp26x.dlb 
	@echo "Linking..."
	$(VDSP)/cc21k.exe .\Debug\rif.doj .\Debug\riftest.doj -T ..\..\VisualDSP_res\Fichiers\ sources\ du\ TP1\ADSP-21262_ASM.LDF -L .\Debug -flags-link -od,.\Debug -o .\Debug\rif_ASMM.dxe -proc ADSP-21262 -flags-link -MM

endif

ifeq ($(MAKECMDGOALS),rif_ASMM_Debug_clean)

rif_ASMM_Debug_clean:
	-$(RM) ".\Debug\rif.doj"
	-$(RM) ".\Debug\riftest.doj"
	-$(RM) "Debug\rif_ASMM.dxe"
	-$(RM) ".\Debug\*.ipa"
	-$(RM) ".\Debug\*.opa"
	-$(RM) ".\Debug\*.ti"
	-$(RM) ".\*.rbld"

endif


