# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_lmb_bram_1/ublaze_system_lmb_bram_1.xci
# IP: The module: 'ublaze_system_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_lmb_bram_1/ublaze_system_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_lmb_bram_1/ublaze_system_lmb_bram_1.xci
# IP: The module: 'ublaze_system_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_lmb_bram_1/ublaze_system_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
