# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/SEG7_upgrade/ip/SEG7_upgrade_clk_wiz_0_0/SEG7_upgrade_clk_wiz_0_0.xci
# IP: The module: 'SEG7_upgrade_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/SEG7_upgrade/ip/SEG7_upgrade_clk_wiz_0_0/SEG7_upgrade_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SEG7_upgrade_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/SEG7_upgrade/ip/SEG7_upgrade_clk_wiz_0_0/SEG7_upgrade_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SEG7_upgrade_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/SEG7_upgrade/ip/SEG7_upgrade_clk_wiz_0_0/SEG7_upgrade_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SEG7_upgrade_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/SEG7_upgrade/ip/SEG7_upgrade_clk_wiz_0_0/SEG7_upgrade_clk_wiz_0_0.xci
# IP: The module: 'SEG7_upgrade_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/SEG7_upgrade/ip/SEG7_upgrade_clk_wiz_0_0/SEG7_upgrade_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SEG7_upgrade_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/SEG7_upgrade/ip/SEG7_upgrade_clk_wiz_0_0/SEG7_upgrade_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SEG7_upgrade_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: u:/Documents/SoC/TP/TP_ublaze_3IS/TP_ublaze_3IS.srcs/sources_1/bd/SEG7_upgrade/ip/SEG7_upgrade_clk_wiz_0_0/SEG7_upgrade_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SEG7_upgrade_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
